auto-converted by polymer-modulizer

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -2,17 +2,11 @@ language: node_js
 sudo: required
 before_script:
   - npm install -g polymer-cli
-  - polymer install --variants
-  - >-
-    npm run update-types && git diff --exit-code || (echo -e
-    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
-    update-types".' && false)
+  - 'npm run update-types && git diff --exit-code || (echo -e ''\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run update-types".'' && false)'
 env:
   global:
-    - secure: >-
-        JibMotHxRDu0L2Fe4raETzvCmvO1CQ0gG7O0XhfGArhuwTC+IW7MLlO/wYpVUkfCLoSKDvIiLSYKpPtUPJ+kZy04VENNc/axKcPdr4iu54se+qe61mRmAunMBVrS21SKlxnqflO1iPFyJ71IyD0/hGBY76Chj4AMUDWhrHJ0WjE=
-    - secure: >-
-        qEULPMDsjwPoNkedrd9azBPPTxckC5hWGKAD8hceTOhoFTxNKKkQmB/Hpx+DomAWXq9yFflB9nRqSTnw9la+Py2bHPWohD9tz+YVsZPvhJmTugrOL+i8B7IzCtncCm7WfWDyjxQFYaHg+UIiEcg9Ci29sNAsWnKakl82e1FJ8oU=
+    - secure: JibMotHxRDu0L2Fe4raETzvCmvO1CQ0gG7O0XhfGArhuwTC+IW7MLlO/wYpVUkfCLoSKDvIiLSYKpPtUPJ+kZy04VENNc/axKcPdr4iu54se+qe61mRmAunMBVrS21SKlxnqflO1iPFyJ71IyD0/hGBY76Chj4AMUDWhrHJ0WjE=
+    - secure: qEULPMDsjwPoNkedrd9azBPPTxckC5hWGKAD8hceTOhoFTxNKKkQmB/Hpx+DomAWXq9yFflB9nRqSTnw9la+Py2bHPWohD9tz+YVsZPvhJmTugrOL+i8B7IzCtncCm7WfWDyjxQFYaHg+UIiEcg9Ci29sNAsWnKakl82e1FJ8oU=
 node_js: stable
 addons:
   firefox: latest
@@ -23,8 +17,7 @@ addons:
       - google-chrome-stable
   sauce_connect: true
 script:
-  - xvfb-run polymer test
-  - >-
-    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
-    fi
+  - xvfb-run polymer test --module-resolution=node --npm
+  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node --npm -s ''default''; fi'
 dist: trusty
+
